Quick fix to remove the compilation issue introduced with the checkin# 1513631
Fixing the below issue:
# 0chain.net/miner/miner
go/src/0chain.net/miner/miner/main.go:120:13: serverChain.updateMiningStake undefined (cannot refer to unexported field or method chain.(*Chain).updateMiningStake)
Removing intermediate container 584325ed18f7
ERROR: Service 'miner' failed to build: The command '/bin/sh -c go build 0chain.net/miner/miner' returned a non-zero code: 2